### ISSUE TITLE
ParentBased spans for remote requests are appearing as root span

### ISSUE THREAD

**Issue by banish1979** [open-telemetry/opentelemetry-php#244]
When ever I generate a ParentBased span, it is appearing as a root span in the Jaeger UI. It is not appearing under the current active span.

This is the part of php code I have written for this.

```
$traceId = $request->headers->get('X-B3-TraceId');
$spanId = $request->headers->get('X-B3-SpanId');

$parentContext = new SpanContext(
    $traceId,
    $spanId,
    1
);
$root = new AlwaysOnSampler();
$sampler = new ParentBased($root);

$sampler->shouldSample(
    $parentContext,
    $traceId,
    $spanId,
    'parent-based',
    API\SpanKind::KIND_SERVER
);

$span = $tracer->startAndActivateSpanFromContext('parent-based', $parentContext, true) ;
$tracer->endActiveSpan();

```

Currently it looks like this: https://www.screencast.com/users/banish1979/folders/Default/media/bd2ab5c9-d47e-4aab-8fb6-617524c42925

I want the span to appear like this: https://www.screencast.com/users/banish1979/folders/Default/media/d3d0f220-6844-426f-8fc0-cd111225b322

Is there anything wrong in this code? Please advice.

**Comment by bobstrecansky** [comment]
@banish1979 - I started looking into this issue; I'm tracking my troubleshooting [here](https://github.com/open-telemetry/opentelemetry-php/compare/main...bobstrecansky:parent_based_spans_test?expand=1)

In your blurb above, I can't see how you've defined your tracer; can you share this with me so I can continue troubleshooting?   If you can provide a more full workable example it'd probably expedite the troubleshooting process.

**Comment by banish1979** [comment]
@bobstrecansky In real time, I am getting the Trace ID and last active Span Id from the header. 

For eg.
Lets say we have a service http://ambassador-01.anish.com/user. This service will generate a Trace ID and then it will create and close a span with the name "ambassador-user". The generated Trace ID and Span ID of "ambassador-user" is attached in the header with the key name "X-B3-TraceId'" and "X-B3-SpanId" and next service is called.

The next service http://api.anish.com/member will grab this "X-B3-TraceId'" and "X-B3-SpanId" and try to create a Span with ParentBased context. Ideally the http://api.anish.com/member service span should appear under "ambassador-user" but it is appearing as root span.

In the following example I am creating a Trace ID and fetching the last active Span Id (Span three) and trying to create a ParentBased Span. But still it is appearing as root span. You can use this code  to run and test the scenario.


```
<?php

declare(strict_types=1);
require __DIR__ . '/../vendor/autoload.php';

use OpenTelemetry\Contrib\Jaeger\Exporter as JaegerExporter;
use OpenTelemetry\Sdk\Trace\Clock;
use OpenTelemetry\Sdk\Trace\Sampler\AlwaysOnSampler;
use OpenTelemetry\Sdk\Trace\Sampler\ParentBased;
use OpenTelemetry\Sdk\Trace\SamplingResult;
use OpenTelemetry\Sdk\Trace\SpanContext;
use OpenTelemetry\Sdk\Trace\SpanProcessor\BatchSpanProcessor;
use OpenTelemetry\Sdk\Trace\TracerProvider;
use OpenTelemetry\Trace as API;

$sampler = new AlwaysOnSampler();
$samplingResult = $sampler->shouldSample(
    null,
    md5((string) microtime(true)),
    substr(md5((string) microtime(true)), 16),
    'io.opentelemetry.example',
    API\SpanKind::KIND_INTERNAL
);

$exporter = new JaegerExporter(
    'alwaysOnJaegerExample',
    'http://jaeger:9412/api/v2/spans'
);

if (SamplingResult::RECORD_AND_SAMPLED === $samplingResult->getDecision()) {
    echo 'Starting AlwaysOnJaegerExample';
    $tracer = (new TracerProvider())
        ->addSpanProcessor(new BatchSpanProcessor($exporter, Clock::get()))
        ->getTracer('io.opentelemetry.contrib.php');

    //Span one opens here
    $span = $tracer->startAndActivateSpan('one');

    //Span two opens here
    $tracer->startAndActivateSpan('two');

    //Span three opens here
    $span = $tracer->startAndActivateSpan('three');

    //Get the Trace id and last active span Id
    $traceId = $span->getContext()->getTraceId();
    $spanId =$span->getContext()->getSpanId();

    //Span three ends here
    $tracer->endActiveSpan();

    //Span two ends here
    $tracer->endActiveSpan();

    //Span one end here
    $tracer->endActiveSpan();

    echo "Trace ID : ".$traceId;
    echo "Span ID : ".$spanId;

    //Creating a parent based span using the Trace ID and the Id of the third Span
    //So parent-based span should come under third span, not as a root span
    $parentContext = new SpanContext(
        $traceId,
        $spanId,
        1
    );
    $root = new AlwaysOnSampler();
    $sampler = new ParentBased($root);

    $sampler->shouldSample(
        $parentContext,
        $traceId,
        $spanId,
        'parent-based',
        API\SpanKind::KIND_INTERNAL
    );

    $span = $tracer->startActiveSpan('parent-based', $parentContext, true) ;
    $tracer->endActiveSpan();


    echo PHP_EOL . 'AlwaysOnJaegerExample complete!  See the results at http://localhost:16686/';
} else {
    echo PHP_EOL . 'AlwaysOnJaegerExample tracing is not enabled';
}

echo PHP_EOL;
```

**Comment by bobstrecansky** [comment]
I was able to get the resulting output that you were looking for by changing L75 in your snippet above from `parent-based` to `one` - the parent based sampler appears to use the span name as the proper delineation point:

https://github.com/open-telemetry/opentelemetry-php/blob/92be0025ea8c85097a3cf0789eb244d34bdab787/sdk/Trace/Sampler/ParentBased.php#L82

Here is my branch where I tested this implementation:
https://github.com/open-telemetry/opentelemetry-php/compare/main...bobstrecansky:parent_based_spans_test?expand=1

Here is a screenshot of the output:

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/4099109/106476142-ba544180-6474-11eb-88fd-32f4a31ea9c7.png">

Hope this helps, happy to discuss further if you are expecting a different outcome or behavior.

**Comment by banish1979** [comment]
@bobstrecansky Changing the span name does not work. I tried it.

Please refer the following screenshot for the expected behavior.

![Screenshot 2021-02-01 at 8 43 51 PM](https://user-images.githubusercontent.com/18693703/106478307-1350c380-64cf-11eb-9481-111bf9b34c23.png)

^ This is the result I am expecting. Kindly refer the PHP code I updated in previous comment. I am passing the SpanId of the Span with the name "three". I want the ParentBased span to appear under the span with the name "three".

**Comment by bobstrecansky** [comment]
We have an active troubleshooting session to investigate this tomorrow.

**Comment by bobstrecansky** [comment]
After investigating further, we realized that you can't create a parent-based span to a non-active span.  If you perform the `$tracer->endActiveSpan();` calls after the creation of the parent-based span, you'll get your expected result.  I have this written in my [troubleshooting branch](https://github.com/open-telemetry/opentelemetry-php/compare/main...bobstrecansky:parent_based_spans_test?expand=1)

Screenshot attached:

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/4099109/106941042-4d4ce000-66f0-11eb-8a26-e2cb4bf3c87b.png">


Does this solve your issue?

**Comment by banish1979** [comment]
@bobstrecansky This will not fix the issue. The method you suggested will create a nested span. We don't have to use ParentBased class to create nested span. Kindly note that the TraceID and SpanID are propagated through headers (X-B3-TraceId & X-B3-SpanId) from one micro service to another. Obviously the developer have to end the active span in their repo.

Let me try to  explain the issue I am facing here. I am getting the TraceID and SpanID to my application (PHP based REST API) from another application (JAVA based API) owned by a different team. The JAVA API will close the span and sent the TraceID and last active SpanID to my PHP API. Since the TraceID and SpanID already exists in the header, the PHP application will try to create a ParentBased span. In the absence of TraceID and SpanID, the PHP API will create a new traceID and propagate downstream. If we are creating a span using ParentBased class then the span should appear under the last span of the JAVA API. That is how the  trace should work,right?

Please note that the TraceID is created on the JAVA API and I don't have any control over that repo which is owned by different team. We can't leave the last span open because it will not sent the span details to collector.

We have tested this implementation in the previous version of Jaeger tracing PHP package and it works fine.
I strongly believe this is something which we need to fix. Because it really important that we keep the hierarchy of the spans correct in the Jaeger UI.

The only difference here is that the JAVA API is using the old version of Jaeger Tracing and PHP API is using Open Telemetry package. Please let me know if you need any info. Thank you so much for looking into this issue. It will be great if we can fix this issue. We already deployed the changes to production. Need to address this ASAP.

**Comment by bobstrecansky** [comment]
Which previous version of the Jaeger tracing PHP package are you referring to?  Maybe we can use that as a reference as to where we are falling short.  

This library is [still in Alpha](https://github.com/open-telemetry/opentelemetry-php#current-project-status).  We will do all that we can to help you to address your issue but I can't promise a resolution in a short time frame.

**Comment by banish1979** [comment]
@bobstrecansky This is the PHP package I was referring to.
"jonahgeorge/jaeger-client-php": "0.4.3"
https://github.com/jonahgeorge/jaeger-client-php

**Comment by bobstrecansky** [comment]
I think this should be fixed with some of the updates in the latest `main` branch.  Would you mind retesting for me?

**Comment by banish1979** [comment]
Tested this again and the issue still remains. 
We added a fix like this in our repo and it did the job.
![image](https://user-images.githubusercontent.com/18693703/112976936-17b5f780-9173-11eb-9f86-6f76f84468f7.png)

**Comment by bobstrecansky** [comment]
This PR has been merged and this issue should be fixed.
